apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJEVU1NWV9TRVJWRVIiOnsidXNlcm5hbWUiOiJEVU1NWV9VU0VSTkFNRSIsInBhc3N3b3JkIjoiRFVNTVlfRE9DS0VSX1BBU1NXT1JEIiwiZW1haWwiOiJEVU1NWV9ET0NLRVJfRU1BSUwiLCJhdXRoIjoiUkZWTlRWbGZWVk5GVWs1QlRVVTZSRlZOVFZsZlJFOURTMFZTWDFCQlUxTlhUMUpFIn19fQ==
type: kubernetes.io/dockerconfigjson
